PATH1=/data1/hecker/eclipseworkspaces/runtime-New_configuration/edu.kit.kastel.scbs.minimalexample/src-gen/
PATH2=/data1/hecker/eclipseworkspaces/runtime-New_configuration/edu.kit.kastel.scbs.minimaladversary/src-gen/

fromPalladio.P : $(PATH1)/*.P $(PATH2)/*.P 
	/bin/cat $^ > $@
